on:
  schedule:
   - cron: "0 3 * * 0"
  workflow_dispatch:

jobs:
  mytask:
    runs-on: ubuntu-latest
    steps:

      #把当前repo当作runner的工作目录
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false   # 禁用默认 GITHUB_TOKEN
    

          
      #先创建文件夹 否则会报错
      #-p表示就算目录已经存在也不会报错
      - name: Create tools directory
        run: mkdir -p ./tools
      
      #下载文件
      - name: "say hello"
        run: |
          echo "hello lantern"
          echo "downloading file"
          curl -L -o ./tools/test.exe https://github.com/getlantern/lantern-binaries/raw/main/lantern-installer-preview.exe
      
      #加密压缩
      - name: "zip files"
        run: 
          zip -r -P "${{ secrets.ZIP_PASSWORD }}" -9 ./tools/photo.zip ./tools/test.exe
          
      #下载完成需要同步信息到git仓库
      - name: Commit and push tools folder
        run: |

          #本次更改人的信息
          git config user.name  "terry"
          git config user.email "terry@hellowolrd.com"
          
          #添加更改到缓存区
          git add ./tools/photo.zip
          
          #把缓存区的信息保存到本地仓库
          git commit -m "Add/update tools folder" ||echo "No changes"  # 文件没有变化时不会报错
          
          #把本地仓库同步到github，必须使用TOKEN，否则出错
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/jianxufx/get_lantern.git HEAD:main
          
