on:
  schedule:
   - cron: "0 3 * * 0"
  workflow_dispatch:

jobs:
  mytask:
    runs-on: ubuntu-latest
    steps:
      - name: "say hello"
        run: |
          echo "hello lantern"
          echo "downloading file"
          curl -L -o test.exe https://github.com/getlantern/lantern-binaries/raw/main/lantern-installer-preview.exe
          ls -lh test.exe
          
