on:
  schedule:
   - cron: "0 3 * * 0"
  workflow_dispatch:

jobs:
  mytask:
    runs-on: ubuntu-latest
    steps:

      #把当前repo当作runner的工作目录
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false   # 禁用默认 GITHUB_TOKEN
    

          
      #先创建文件夹 否则会报错
      #-p表示就算目录已经存在也不会报错
      - name: Create tools directory
        run: mkdir -p ./tools
      
      #下载文件
      - name: "say hello"
        run: |
          echo "hello lantern"
          echo "downloading file"
          curl -L -o ./tools/test.exe https://github.com/getlantern/lantern-binaries/raw/main/lantern-installer-preview.exe
      
      
      #重命名文件为随机名称
      - name: Rename EXE to random file name
        run: |
          filename=("PPT设计" "客户要的方案" "给弟弟准备的实习报告" "自己设计的rpg游戏" "三亚旅游攻略" "老板要的" " 记得明天发给BOSS" "第N版" "第11111111版" "images" "不想上这个班")
          lastname=("rar" "zip" "7z" "doc" "docx" "ppt" "pptx" "pdf" )
  
          index_filename=$(( RANDOM % ${#filename[@]} ))
          index_lastname=$(( RANDOM % ${#lastname[@]} ))
          FILENAME="${filename[$index_filename]}_$(date +%Y.%m.%d).${lastname[$index_lastname]}"
          mv ./tools/test.exe ./tools/"$FILENAME"
          echo "重命名为: $FILENAME"
          
      #安装upx 和zip
   
          sudo apt update && sudo apt install -y upx zip
      #压缩 并加密码
          upx --best --lzma ./tools/"$FILENAME"
          zip -r -P "${{ secrets.ZIP_PASSWORD }}" -9 ./tools/123.zip  ./tools/"$FILENAME"
          
      #下载完成需要同步信息到git仓库
      - name: Commit and push tools folder
        run: |

          #本次更改人的信息
          git config user.name  "terry"
          git config user.email "terry@hellowolrd.com"
          
          #添加更改到缓存区
          git add ./tools/123.zip
          
          #把缓存区的信息保存到本地仓库
          git commit -m "Add/update tools folder" ||echo "No changes"  # 文件没有变化时不会报错
          
          #把本地仓库同步到github，必须使用TOKEN，否则出错
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/jianxufx/get_lantern.git HEAD:main
          
